package pe.edu.unsch.entities;
// Generated 16-jul-2019 11:02:14 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Color generated by hbm2java
 */
public class Color implements java.io.Serializable {

	private int idcolor;
	private String nombre;
	private Set productos = new HashSet(0);

	public Color() {
	}

	public Color(int idcolor, String nombre) {
		this.idcolor = idcolor;
		this.nombre = nombre;
	}

	public Color(int idcolor, String nombre, Set productos) {
		this.idcolor = idcolor;
		this.nombre = nombre;
		this.productos = productos;
	}

	public int getIdcolor() {
		return this.idcolor;
	}

	public void setIdcolor(int idcolor) {
		this.idcolor = idcolor;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getProductos() {
		return this.productos;
	}

	public void setProductos(Set productos) {
		this.productos = productos;
	}

}
