package pe.edu.unsch.entities;
// Generated 16-jul-2019 11:02:14 by Hibernate Tools 5.3.0.Beta2

/**
 * ProductoId generated by hbm2java
 */
public class ProductoId implements java.io.Serializable {

	private int idproducto;
	private String nombre;
	private long precio;
	private int cantidad;
	private String descripcion;
	private String imagen;
	private byte caracteristica;
	private int idcategoria;
	private int idcolor;
	private int idmarca;

	public ProductoId() {
	}

	public ProductoId(int idproducto, String nombre, long precio, int cantidad, String descripcion, String imagen,
			byte caracteristica, int idcategoria, int idcolor, int idmarca) {
		this.idproducto = idproducto;
		this.nombre = nombre;
		this.precio = precio;
		this.cantidad = cantidad;
		this.descripcion = descripcion;
		this.imagen = imagen;
		this.caracteristica = caracteristica;
		this.idcategoria = idcategoria;
		this.idcolor = idcolor;
		this.idmarca = idmarca;
	}

	public int getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(int idproducto) {
		this.idproducto = idproducto;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public long getPrecio() {
		return this.precio;
	}

	public void setPrecio(long precio) {
		this.precio = precio;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	public byte getCaracteristica() {
		return this.caracteristica;
	}

	public void setCaracteristica(byte caracteristica) {
		this.caracteristica = caracteristica;
	}

	public int getIdcategoria() {
		return this.idcategoria;
	}

	public void setIdcategoria(int idcategoria) {
		this.idcategoria = idcategoria;
	}

	public int getIdcolor() {
		return this.idcolor;
	}

	public void setIdcolor(int idcolor) {
		this.idcolor = idcolor;
	}

	public int getIdmarca() {
		return this.idmarca;
	}

	public void setIdmarca(int idmarca) {
		this.idmarca = idmarca;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductoId))
			return false;
		ProductoId castOther = (ProductoId) other;

		return (this.getIdproducto() == castOther.getIdproducto())
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& (this.getPrecio() == castOther.getPrecio()) && (this.getCantidad() == castOther.getCantidad())
				&& ((this.getDescripcion() == castOther.getDescripcion())
						|| (this.getDescripcion() != null && castOther.getDescripcion() != null
								&& this.getDescripcion().equals(castOther.getDescripcion())))
				&& ((this.getImagen() == castOther.getImagen()) || (this.getImagen() != null
						&& castOther.getImagen() != null && this.getImagen().equals(castOther.getImagen())))
				&& (this.getCaracteristica() == castOther.getCaracteristica())
				&& (this.getIdcategoria() == castOther.getIdcategoria())
				&& (this.getIdcolor() == castOther.getIdcolor()) && (this.getIdmarca() == castOther.getIdmarca());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdproducto();
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (int) this.getPrecio();
		result = 37 * result + this.getCantidad();
		result = 37 * result + (getDescripcion() == null ? 0 : this.getDescripcion().hashCode());
		result = 37 * result + (getImagen() == null ? 0 : this.getImagen().hashCode());
		result = 37 * result + this.getCaracteristica();
		result = 37 * result + this.getIdcategoria();
		result = 37 * result + this.getIdcolor();
		result = 37 * result + this.getIdmarca();
		return result;
	}

}
