package pe.edu.unsch.entities;
// Generated 16-jul-2019 11:02:14 by Hibernate Tools 5.3.0.Beta2

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private ProductoId id;
	private Categoria categoria;
	private Color color;
	private Marca marca;

	public Producto() {
	}

	public Producto(ProductoId id, Categoria categoria, Color color, Marca marca) {
		this.id = id;
		this.categoria = categoria;
		this.color = color;
		this.marca = marca;
	}

	public ProductoId getId() {
		return this.id;
	}

	public void setId(ProductoId id) {
		this.id = id;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public Color getColor() {
		return this.color;
	}

	public void setColor(Color color) {
		this.color = color;
	}

	public Marca getMarca() {
		return this.marca;
	}

	public void setMarca(Marca marca) {
		this.marca = marca;
	}

}
